# Generated by Django 4.0.5 on 2022-07-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=True, max_length=100, verbose_name='title'),
        ),
    ]
