# Generated by Django 4.0.5 on 2022-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
    ]
